<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>SYUAS</AssemblyName>
    <ApplicationIcon>Assets/Syuas.ico</ApplicationIcon>
    <RootNamespace>Syuas.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Syuas.Core/Syuas.Core.csproj" />
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <EmbeddedResource Include="Highlighting/AsciiDoc.xshd" />
    <Resource Include="Assets/Syuas.ico" />
    <Content Include="PreviewAssets/**" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
